# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details.
{
    'name': 'wordpress connctor odoo',
    'version': '15.0.7.0.1',
    'license': 'AGPL-3',
    'category': 'Sales',
    'summary': 'The Odoo WordPress Connector facilitates the automation of crucial '
               'business operations in Odoo by enabling a two-way exchange of data between WooCommerce and Odoo.',

    'author': 'MMH.',
    'maintainer': 'MMH COMPANY',
    'depends': ['common_connector_library'],
    'data': [
        'security/group.xml',
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'data/ir_sequence.xml',
        'data/ir_cron_data.xml',
        'data/import_order_status_ept.xml',
        'wizard/manual_queue_process_ept.xml',
        'wizard/cron_configuration_ept.xml',
        'views/instance_main_menu_view.xml',
        'wizard/process_import_export_view.xml',
        'views/product_image_ept.xml',
        'views/product_template_view.xml',
        'views/sale_workflow_config.xml',
        'wizard/res_config_view.xml',
        'views/product_data_queue_ept_view.xml',
        'views/product_data_queue_line_ept_view.xml',
        'views/product_variant_view.xml',
        'views/tags_ept.xml',
        'views/product_attribute_view.xml',
        'views/product_attribute_term_view.xml',
        'views/product_category_view.xml',
        'views/customer_data_queue_ept.xml',
        'views/customer_data_queue_line_ept.xml',
        'views/order_data_queue_ept.xml',
        'views/order_data_queue_line_ept.xml',
        'views/webhook_ept.xml',
        'views/common_log_book_ept.xml',
        'views/woo_instances_onboarding_panel_view.xml',
        'views/sale_order.xml',
        'views/stock_picking_view.xml',
        'views/res_partner.xml',
        'views/payment_gateway.xml',
        'views/account_move_view.xml',
        'views/instance_view.xml',
        'wizard/cancel_refund_order_wizard.xml',
        'wizard/financial_status_onboarding_view.xml',
        'wizard/basic_configuration_onboarding.xml',
        'wizard/woo_onboarding_confirmation_ept.xml',
        'views/coupons_ept.xml',
        'views/coupon_data_queue_ept.xml',
        'views/coupon_data_queue_line_ept.xml',
        'wizard/prepare_product_for_export.xml',
        'report/sale_report.xml',
        'wizard/instance_configuration_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': ["/woo_commerce_mh/static/src/js/woo_button_collapse.js"]
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'active': False,
    'price': 280.00,
    'currency': 'USD',
    'cloc_exclude': ["woocommerce/**/*",
                     "wordpress_xmlrpc/**/*",
                     "**/*.xml"],

}
